import sys
import json
from antlr4 import * # pyright: ignore[reportWildcardImportFromLibrary]
from dfyPyParse.dafnyLexer import dafnyLexer
from dfyPyParse.dafnyParser import dafnyParser
from dfyPyParse.dafnyVisitor import dafnyVisitor

# [AI DISCLOSURE] - I don't know how ANTLR works, so I generated this and 
# have commented how it works after thouroughly going over it. Added an 
# optimization which prevents needing to go back up the tree at one point.

class DafnyJSONVisitor(dafnyVisitor):
    def __init__(self):
        self.methods = []
        self.current_method = None
        self.state = {}

    def visitProgram(self, ctx: dafnyParser.ProgramContext):
        self.visitChildren(ctx) # ctx is always the "current node" in the AST
        return self.methods

    def visitMethodDecl(self, ctx: dafnyParser.MethodDeclContext): 
        # methodDecl in dafny.g4, similar names were generated by our ANTLR environment for other visits.

        # Reset state at the start of every method so data doesn't leak
        self.state = {}

        sig = ctx.methodSignatureDecl()
        # method signature - method identifier
        # "methodSignatureDecl: METHOD (identifier | upperIdentifier) parameters (RETURNS parameters)? verifierAnnotation*;"

        method_name = sig.identifier().getText() if sig.identifier() else sig.upperIdentifier().getText()
        
        self.current_method = {
            "method_name": method_name,
            "loops": [],
            "preconditions": [],
            "postconditions": [],
            "parameters": [],
            "returns": []
        }

        # input parameters
        if sig.parameters():
            self.current_method["parameters"] = self.extract_params(sig.parameters(0))
            # check below for extract_params

        # return parameters, if they exist
        if len(sig.parameters()) > 1:
            self.current_method["returns"] = self.extract_params(sig.parameters(1))

        # preconditions and postconditions
        for note in sig.verifierAnnotation():
            if note.requires():
                self.current_method["preconditions"].append(note.requires().expression().getText())
            elif note.ensures():
                self.current_method["postconditions"].append(note.ensures().expression().getText())

        if ctx.sequence():
            self.visit(ctx.sequence())
            # our class wraps around dafnyVisitor, this function is internal to the library. blackbox it away :)
            # moves into the method body (children nodes) after extracting what it could 
            # at the method layer (parent)

        self.methods.append(self.current_method)
        self.current_method = None
        return
    
    # name and type of parameter variables
    def extract_params(self, params_ctx):
        results = []
        if not params_ctx.identifierType():
            return results
        for p in params_ctx.identifierType():
            results.append({
                "name": p.identifier().getText(), 
                "type": p.type_().getText()
            })
        return results


    def visitDeclaration(self, ctx: dafnyParser.DeclarationContext):
        # finds variable declarations to capture their initial states
        
        lhs_ctx = ctx.declarationLhs()
        lhs_vars = [item.getText() for item in lhs_ctx.declAssignLhs()] # cases like var x,y := 1,2
        
        rhs_ctx = ctx.declAssignRhs()
        if isinstance(rhs_ctx, list):
             rhs_vals = [item.getText() for item in rhs_ctx] # cases like var x,y := 1,2
        else:
             rhs_vals = [rhs_ctx.getText()] # normal declarations, var i := 0

        for i, var_name in enumerate(lhs_vars):    
            self.state[var_name] = rhs_vals[i]

        self.visitChildren(ctx)

    def visitUpdate(self, ctx: dafnyParser.AssignmentContext):
        # same idea as decleration - some declared variables may get updated before the loop starts.
        # we want to keep track of their states exactly as they were before the loop began
        
        lhs_list = ctx.assignmentLhs()
        rhs_list = ctx.declAssignRhs()

        lhs_vars = [item.getText() for item in lhs_list]
        rhs_vals = [item.getText() for item in rhs_list] if isinstance(rhs_list, list) else [rhs_list.getText()]

        for i, var_name in enumerate(lhs_vars):
            self.state[var_name] = rhs_vals[i]
        
        self.visitChildren(ctx)

    def visitWhileStatement(self, ctx: dafnyParser.WhileStatementContext):
        # same idea as methodDecl - figure out what's up in the while loop
        if self.current_method is None: return

        # capture invariants
        invariants = []
        if ctx.verifierAnnotation():
            for note in ctx.verifierAnnotation():
                if note.invariant():
                    invariants.append(note.invariant().expression().getText())

        # loop body variables
        variables = self.analyze_loop_variables(ctx.sequence()) # important, check downstream

        loop_obj = {
            "type": "while",
            "condition": ctx.expression().getText(),
            "variables": variables,
            "invariants": invariants
        }
        self.current_method["loops"].append(loop_obj)

        # important: visit children so assignments INSIDE loop 
        # update the state for any code that follows.
        self.visitChildren(ctx)

    def visitForLoop(self, ctx: dafnyParser.ForLoopContext):
        # largely same idea as while loops
        if self.current_method is None: return

        invariants = []
        if hasattr(ctx, 'verifierAnnotation') and ctx.verifierAnnotation():
             for note in ctx.verifierAnnotation():
                if note.invariant():
                    invariants.append(note.invariant().expression().getText())

        loop_var = ctx.identifier().getText()
        start_expr = ctx.expression(0).getText()
        end_expr = ctx.expression(1).getText()
        
        # for loop doesnt initialise "i" (loop increment) beforehand, 
        # needs to get added so we can interpret properly!
        # We add it to the backpack immediately so nested logic can see it.
        self.state[loop_var] = start_expr
        
        variables = self.analyze_loop_variables(ctx.sequence())

        # Explicitly add the loop counter to the variables list
        variables.insert(0, {
            "name": loop_var,
            "type": "int",
            "init": start_expr,
            "trans": f"{loop_var} + 1"
        })

        loop_obj = {
            "type": "for",
            "condition": f"{loop_var} < {end_expr}", 
            # condition in for loops is fixed. not limits inclusive
            # https://dafny.org/dafny/DafnyRef/DafnyRef#sec-for-statement
            "variables": variables,
            "invariants": invariants
        }
        self.current_method["loops"].append(loop_obj)
        
        self.visitChildren(ctx)

    def analyze_loop_variables(self, body_sequence):
        # find variable transitions in the loop body
        updates = self.scan_assignments(body_sequence)
        results = []

        for var_name, assignment_expr in updates.items():
            initial_val = self.state.get(var_name, None) # get initial vals from state
            
            results.append({
                "name": var_name,
                "type": "int",
                "init": initial_val,
                "trans": assignment_expr # get transition assignment from scan_for_updates()
            })
        return results

    def scan_assignments(self, sequence_ctx):
        # finds variables updates/assignments, same logic as visitDeclaration

        updates = {}
        if not sequence_ctx or not sequence_ctx.statement(): 
            return updates

        for stmt in sequence_ctx.statement():
            if stmt.assignment():
                assign = stmt.assignment()
                lhs_list = assign.assignmentLhs()
                rhs_list = assign.declAssignRhs()
                
                lhs_texts = [x.getText() for x in lhs_list]
                rhs_texts = [x.getText() for x in rhs_list] if isinstance(rhs_list, list) else [rhs_list.getText()]

                for i, var_name in enumerate(lhs_texts):
                    updates[var_name] = rhs_texts[i]

        return updates

def main(argv):
    input_stream = FileStream(argv[1], encoding='utf-8')
    lexer = dafnyLexer(input_stream)
    stream = CommonTokenStream(lexer)
    parser = dafnyParser(stream)
    tree = parser.program()

    visitor = DafnyJSONVisitor()
    methods_data = visitor.visit(tree) # start visiting from the root of the tree

    print(json.dumps(methods_data, indent=2))

if __name__ == '__main__':
    if len(sys.argv) > 1:
        main(sys.argv)
    else:
        print("Usage: parser.py <your_file>.dfy")